const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const repo = path.resolve(__dirname, '../..');
const raw = path.join(repo, '.yarn/simplification-evidence/031');
const originalRoot = path.join(repo, '.yarn/.codex-worktrees/ts7-native-stacked');
const sourcePath = path.join(originalRoot, 'scripts/benchmark-backends.mjs');
const sourceBytes = fs.readFileSync(sourcePath);
const hash = data => crypto.createHash('sha256').update(data).digest('hex');
assert.equal(hash(sourceBytes), 'f5dcde4895b27f948d2158acba86199b0abbec1f2f3f5aed0b60ed9b92a60bd0');
let source = sourceBytes.toString().replaceAll('\r\n', '\n');
const oldRoot = 'const REPOSITORY_ROOT = path.dirname(\n  fileURLToPath(new URL("../package.json", import.meta.url)),\n);';
assert(source.includes(oldRoot));
source = source.replace(oldRoot, `const REPOSITORY_ROOT = ${JSON.stringify(originalRoot)};`);
const footer = '\ntry {\n  const options = parseArguments(process.argv.slice(2));';
assert.equal(source.indexOf(footer), source.lastIndexOf(footer));
assert(source.includes(footer));
source = source.slice(0, source.indexOf(footer)) + '\nexport { readBenchmarkWorkspace, writeSharedRevision, loadPluginRunner, normalizeOutput };\n';
fs.writeFileSync(path.join(raw, 'backend-library.mjs'), source, { flag: 'wx' });
fs.writeFileSync(path.join(__dirname, 'library-provenance.json'), JSON.stringify({ sourcePath, sourceSha256: hash(sourceBytes), librarySha256: hash(source), changes: ['Pin original repository root.', 'Replace CLI entrypoint with exports of unchanged runner/helper functions.'] }, null, 2) + '\n', { flag: 'wx' });
